server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9014

applicationConfig:
  applicationVersionFilePath:
  mongoDbConf:
    url: localhost
    port: 27017
    database: rh
  rooms:
  -
    type: TWIN
    floor: GROUND
  -
    type: DOUBLE
    floor: GROUND
  -
    type: TWIN
    floor: FIRST
  -
    type: DOUBLE
    floor: FIRST
  -
    type: SUITE
    floor: FIRST